#Site Info
title: jepetolee's Insight
tagline: 'for Study & Insight'
description: 'for Study & Insight'
url: https://jepetolee.github.io
logo: public/logo.png
encoding: utf-8

#Site Configure
gems:
   - jekyll-paginate
markdown: kramdown
kramdown:
      input: GFM
excerpt_separator: "<!-- more -->"
sass:
    style: compressed
    sass_dir: _scss
paginate: 5
paginate_path: '/insight/page:num'
permalink: pretty
version: 1.0.0

# About/contact

author:
    name: jepetolee
    description1: <strong>I'll prove myself </strong>
    description2: 천번의 연습을 단(鍛), 만번의 연습을 련(練)이라고 한다.
    gravatar: 57299826b9d09990732b37f92137aa71
    contact:
        linkedin: https://www.linkedin.com/in/lee-jepeto-7b27781b3/
        github: https://github.com/jepetolee
        email: mailto:jepetolee@gmail.com

#Navigation 
nav:
  Home:
     - '/'
  Contents:
    - '/insight/'
    - { Posts: '/insight/posts/' }
    - { Tags: '/insight/tags/' }
  About:
    - '/about/'

# Where are tags and posts displayed
tage_page: '/insight/tags/'
post_page: '/insight/posts/'

pagein:
    image: https://jepetolee.github.io/public/img/intro.jpg
    caption: 새로운 시대가 오길 기다리지 말고 너의 손으로 세상의 새로운 시대를 열어라

# Plugins
mathjax: true
google_analytics_token: 'G-9F6FRCP1DK'
